name: Doxygen Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          doxygen -v

      - name: Generate Documentation
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs
          # Run Doxygen (assuming Doxyfile is in root)
          doxygen Doxyfile || (echo "Doxygen failed"; exit 1)
          # Verify HTML output
          if [ ! -d "docs/html" ]; then
            echo "Error: docs/html not found!"
            ls -R docs  # Debug: show directory contents
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html
          keep_files: false
